media: assets/covers
content:
  - name: books
    label: Books
    type: file
    list: true
    path: public/books.json
    fields:
      - { name: isbn, label: ISBN, type: string }
      - { name: owned, label: Posiadane?, type: boolean, default: true}
      - { name: cover, label: Okładka, type: image }
      - { name: language, label: Język, type: string }
      - { name: region, label: Region, type: string }
      - { name: country, label: Kraj, type: select }
      - { name: continent, label: Kontynent, type: select, options: { 
        values: [ 
          Afryka,
          Antarktyda,
          Azja,
          Europa,
          Ameryka Północna,
          Australia,
          Ameryka Południowa,
          ] } }
      - { name: translator, label: Tłumaczenie, type: string }
      - { name: title, label: Tytuł, type: string }
      - { name: year, label: Rok, type: string }
      - { name: author, label: Autor, type: string, default: "Antoine de Saint-Exupéry" }
      