media: assets/covers
content:
  - name: books
    label: Books
    type: file
    path: public/books.json
    fields:
      - { name: isbn, label: ISBN, type: string }
      - { name: owned, label: Posiadane?, type: boolean, default: trie }
      - { name: cover, label: Okładka, type: image }
      - { name: language, label: Język, type: string, options: {} }
      - { name: comments, label: Comments, type: boolean, default: true }
      - { name: description, label: Description, type: string, options: { 
        values: [ 
          Polski, 
          Angielski, 
          Hiszpański 
          ] } }
      - name: tag
        label: Tag
        type: select
        options:
          values:
          - value: bob
          - value: patricia
          - value: alice
      - { name: image, label: Image, type: image }
      - { name: body, label: Body, type: rich-text }