media: assets/covers
content:
  - name: books
    label: Books
    type: file
    path: public/books.json
    fields:
      - { name: isbn, label: ISBN, type: string }
      - { name: owned, label: Posiadane?, type: boolean, default: trie }
      - { name: cover, label: Okładka, type: image }
      - { name: language, label: Język, type: select, options: { 
        values: [ 
          Polski, 
          Angielski, 
          Hiszpański 
          ] } }
      - name: language
        label: Język
        type: select
        options:
          values:
            - bob
            - patricia
            - alice
      - { name: image, label: Image, type: image }
      - { name: body, label: Body, type: rich-text }