media: assets/covers
content:
  - name: books
    label: Books
    type: file
    list: true
    path: public/books.json
    fields:
      - { name: isbn, label: ISBN, required: true, type: string }
      - { name: owned, label: Posiadane?, type: boolean, default: true }
      - { name: cover, label: Okładka, type: image }
      - { name: language, label: Język, required: true, type: string }
      - { name: region, label: Region, type: string }
      - { name: country, label: Kraj, required: true, type: string }
      - { 
          name: continent, 
          label: Kontynent, 
          type: select, 
          required: true, 
          options: { 
            values: [ 
              Afryka,
              Antarktyda,
              Azja,
              Europa,
              Ameryka Północna,
              Australia,
              Ameryka Południowa
            ] 
          } 
        }
      - { name: publisher, label: Wydawnictwo, type: string }
      - { name: translator, label: Tłumaczenie, type: string }
      - { name: title, label: Tytuł, required: true, type: string }
      - { name: year, label: Rok, type: number }
      - { name: author, label: Autor, type: string, default: "Antoine de Saint-Exupéry" }