media: assets/covers
content:
  - name: books
    label: Books
    type: file
    path: public/books.json
    fields:
      - { name: isbn, label: ISBN, type: string }
      - { name: owned, label: Posiadane?, type: boolean, default: trie }
      - { name: cover, label: Okładka, type: image }
      - { name: language, label: Język, type: select, options: { 
        values: [ 
          Polski, 
          Angielski, 
          Hiszpański,
          ] } }
      - { name: region, label: Region, type: string }
      - { name: country, label: Kraj, type: select, options: { 
        values: [ 
          Polska, 
          Niemcy, 
          Hiszpania,
          ] } }
      - { name: continent, label: Kontynent, type: select, options: { 
        values: [ 
          Afryka,
          Antarktyda,
          Azja,
          Europa,
          Ameryka Północna,
          Australia,
          Ameryka Południowa,
          ] } }